### ISSUE TITLE
Clarify flake8 validation codes and messages in README

### ISSUE THREAD

**Issue by peterjc** [sbdchd/flake8-pie#13]
I didn't initially see the flake8 validation codes in your README as they were part of section titles. You also don't list the actual error messages which could help with Google searches etc (and would have likely caught the typos fixed in #12 earlier).

How about a simple table at the start of the lints section?

* PIE781: You are assigning to a variable and then returning. Instead remove the assignment and return.
* PIE782: Unnecessary f-string. You can safely remove the `f` sigil.

I'd also document the meaning behind the number 781 (if there is one) and abbreviation PIE (which puzzles me).

P.S. Would you be happy with "prefix" rather than "sigil" in PIE782?

**Comment by sbdchd** [comment]
I think the numbers and the abbreviation just have to be unique so when someone else creates a flake8 plugin the lint error codes don't overlap. Previously flake8-pie used "B" as a prefix but that turned out to overlap with [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear).

Also I agree that "prefix" is probably more clear than ["sigil"](https://en.wikipedia.org/wiki/Sigil_(computer_programming)).
Seems that the [PEP that added f-strings](https://www.python.org/dev/peps/pep-0498/) uses the term prefix as well.

**Comment by peterjc** [comment]
That makes sense, ``flake8-bugbear`` has no codes in the 700 range (currently). Thanks.

What does PIE stand for (if anything)?

Shall I make a pull request for sigil/prefix?

**Comment by sbdchd** [comment]
The PIE is just a reference to flake8-*pie*.

The "b" prefix overlapped which caused errors.
Here is the relevant issue: https://github.com/sbdchd/flake8-pie/issues/9

Already done on the sigil/prefix front: https://github.com/sbdchd/flake8-pie/pull/16

**Comment by peterjc** [comment]
I'm still puzzled by "pie" in the project name ``flake8-pie`` (which naturally becomes an upper case PIE for the validation code prefix), but thank you - otherwise #16 has addressed my queries.

**Comment by sbdchd** [comment]
Should be fixed in the latest release: 0.2.2 https://pypi.org/project/flake8-pie/#history

**Comment by sbdchd** [comment]
Python -> .py -> pie was my thinking
